name: Deploy to Neocities

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 19
      - name: Uproot site
        run: |
          npm install
          npm run build
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v1.1.20
        with:
          key: ${{ secrets.NEOCITIES_API_KEY }}
          dist_dir: site # /static/ is uploaded manually via WebDAV, this might change
          cleanup: true